version: '3.6'
services:
  kafka-cluster:
    image: landoop/fast-data-dev:cp3.3.0

    environment:
      ADV_HOST: 192.168.0.130                   # Mudar para 192.168.99.100 se usar Docker Toolbox
      RUNTESTS: 0                           # Desabilita testes
      FORWARDLOGS: 0
      SAMPLEDATA: 0

    ports:
        - "2181:2181"                       # Zookeeper
        - "3030:3030"                       # Landoop UI
        - "8081-8083:8081-8083"             # REST Proxy, Schema Registry, Kafka Connect ports
        - "9581-9585:9581-9585"             # JMX Ports
        - "9092:9092"                       # Kafka Broker

# Confluent Platform
# docker run -it --rm --net=host confluentinc/cp-schema-registry:3.3.1 bash